server:
  port: 8761

spring:
  application:
    name: discoveryserver

eureka:
  instance:
    hostname: ${DISCOVERY_SERVER_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
