server:
  port: 8085

spring:
  application:
        name: email-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
      value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer

  mail:
    host: smtp.example.com
    port: 587
    username: vikas1306v@gmail.com
    password: ijkm eoax hmoz efuj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
